### ISSUE TITLE
Questions about the dynamics part

### ISSUE THREAD

**Issue by widthstudio** [haruki1526/LeggedRobotsForBulletGifs#1]
hello sir! Question about the implementation of the dynamics code? eg.def M(self) ,how do you get this? It doesn't seem quite what I learned.

**Comment by haruki1526** [comment]
What does "def M(self)" mean?
Do you mean you want to write code to get dynamics parameters such as mass?

**Comment by widthstudio** [comment]
I mean, I want to know how the mass matrix, the gravity matrix, the centrifugal force matrix are computed in your dynamics.&nbsp;How is the code in the image implemented








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haruki ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 晚上10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haruki1526/LeggedRobotsForBulletGifs] Questions about the dynamics part (Issue #1)





 
“def M(self)”是什么意思？
 您的意思是要编写代码来获取质量等动力学参数吗？
 
—
您收到此消息是因为您创作了该线程。
直接回复本邮件，在 GitHub 上查看，或退订。
使用 GitHub Mobile for iOS或Android随时随地分类通知。

**Comment by haruki1526** [comment]
mass matrix, gravity matrix, etc. in `inverse_dynamics.py` has nothing to do with the behavior of the gif image.
 `inverse_dynamics.py` is for 3DOF Inverse Dynamics. However, the behavior in the image is realized by Inverse Kinematics.

 I referred to [this book](https://www.amazon.co.jp/%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88%E5%88%B6%E5%BE%A1%E5%9F%BA%E7%A4%8E%E8%AB%96-%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF%E5%88%B6%E5%BE%A1%E6%A9%9F%E6%A2%B0%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA-%E5%90%89%E5%B7%9D-%E6%81%92%E5%A4%AB/dp/4339041300/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88%E5%88%B6%E5%BE%A1%E5%9F%BA%E7%A4%8E%E8%AB%96&qid=1638450518&sr=8-1) when I implemented Inverse Dynamics. 
Although it is written in Japanese, there is also an [English translation](https://www.amazon.co.jp/Foundations-Robotics-Analysis-Tsuneo-Yoshikawa/dp/0262240289/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=Foundations+of+Robotics&qid=1638450566&sr=8-1).

**Comment by widthstudio** [comment]
Thanks, since I didn't understand your inverse dynamics, that's why I asked you about it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haruki ***@***.***&gt;; 
发送时间: 2021年12月2日(星期四) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haruki1526/LeggedRobotsForBulletGifs] Questions about the dynamics part (Issue #1)





 
mass matrix, gravity matrix, etc. in inverse_dynamics.py has nothing to do with the behavior of the gif image.
 inverse_dynamics.py is for 3DOF Inverse Dynamics. However, the behavior in the image is realized by Inverse Kinematics.
 
I referred to this book when I implemented A.
 Although it is written in Japanese, there is also an English translation.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haruki1526** [comment]
Inverse Dynamics is implemented by Lagrangian equations.
Sorry, it would take too long to explain here, so I introduced this book. 
Please refer to the dynamics section of the book for more details.

**Comment by widthstudio** [comment]
anyway，thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haruki ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haruki1526/LeggedRobotsForBulletGifs] Questions about the dynamics part (Issue #1)





 
Inverse Dynamics is implemented by Lagrangian equations.
 Sorry, it would take too long to explain here, so I introduced this book.
 Please refer to the dynamics section of the book for more details.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
